notification :growl

group :tests do
  guard 'rspec', :cli => '--color' do
    watch(%r{^spec/.+_spec\.rb$})
    watch(%r{^lib/(.+)\.rb$}) { 'spec' }
    watch('spec/spec_helper.rb') { 'spec' }
  end
end
interactor :off
